### ISSUE TITLE
WPS not installing 

### ISSUE THREAD

**Issue by metroid2012** [whatheway/WRF-4.3-install-script-linux-64bit#5]
Hi,
I tested this last version of the script and found that the downloading neither the compiling of WPS worked. Could you correct this please?

**Comment by whatheway** [comment]
I believe I have fixed this issue.  Can you confirm with the latest version of the script?

**Comment by metroid2012** [comment]
it should normally work now. Thank you very much for the modifications. Have you done something with adding the MET tool?

**Comment by whatheway** [comment]
Which met tool are you referring to?

**Comment by metroid2012** [comment]
Since this is the meteorological version of the model, i've suggested previously that the script should contain the model evaluation tools ( MET) installation as well. With this manner we'll get a robust script.

**Comment by whatheway** [comment]
There are a few included in the script that I have used in the past.
They are UPP, ARWPOST, Opengrads, WPS domain tool, and WRF portal tool.

Is there another one that you are looking for?  If it is easily added and
freely available I can see about adding it to the scripts.

**Comment by whatheway** [comment]
I found the tools you're talking about.  I can try to add them into the
scripts. I haven't worked with them before so it may take some time to make
sure they work properly.

Alternatively, if you are familiar with the installation of them. You could
do a pull request on GitHub for the script and I can add it into the code
once you have it installed properly.
