### ISSUE TITLE
library installation issue

### ISSUE THREAD

**Issue by zexhan07** [whatheway/WRF-4.3-install-script-linux-64bit#6]
hey! can anybody help me? how can i add a permanently path. after restarting my linux they ask me to reinstall the libraries. i added this path "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib" but it seems it's not working. thanks

**Comment by whatheway** [comment]
Load everything up and then use these commands at the end.  They will put them into your permanent path


## export PATH and LD_LIBRARY_PATH
echo "export PATH=$DIR/bin:$PATH" >> ~/.bashrc
echo "export LD_LIBRARY_PATH=$DIR/lib:$LD_LIBRARY_PATH" >> ~/.bashrc
