### ISSUE TITLE
sed: -e expression #1, char 32: unknown option to `s'

### ISSUE THREAD

**Issue by zexhan07** [whatheway/WRF-4.3-install-script-linux-64bit#7]
sed -i -e 's/-lnetcdf/-lnetcdff -lnetcdf/g' $HOME/WRF/ARWpost/src/Makefile this gives an error when i try to run it. error: sed: -e expression #1, char 32: unknown option to `s'

**Comment by whatheway** [comment]
Could be related to the previous issue with libraries not loading correctly.  I have updated the scripts to make sure they are all pointing to proper web-links.   I will test everything out and if you can test it too that would be helpful.
